### PR TITLE
Considering relative aspect ratio of images

### PR DESCRIPTION
**Pull request by bguidolim**
From this:
IMG_0003

To this:
IMG_0002

### CODE REVIEW

**Review by andyfinnell — COMMENTED** [review]
Hey, thanks for the PR. I want to take a little bit of time to think about this though. While constraining the image to the current line is useful, other times one might want it to stretch the line (allow things to scroll horizontally), or to constrain the image to the line height (think emoji). I'll work on a solution that allows this approach, plus the others.

**Comment by bguidolim** [comment]
Hi! Sure, take your time, however I would like to present to you some reasons why I created this PR:

- The text itself already has this behavior of no expanding horizontally, but vertically. So doing this with image is basically keeping the same pattern.
- Because of the reason above, there is no way to enable the horizontal scrolling anyway, but even forcing the horizontal scrolling, the text is not following the image.
- There is always the possibility to add a link to the image to redirect the user to the full-size image.

Regarding the emoji, currently it's considered as a text, so it will follow the text behavior, right?

IMO, it does make sense to think in a general approach, but this PR looks more like a fix to match how text and images behave.

**Comment by andyfinnell** [comment]
To clarify a bit:

The text can expand horizontally, but as you noted, it is not the default. For example, you can dump the NativeMarkLabel in a scroll view without pinning the label's width and it will scroll horizontally. It's not super-useful on iOS, but it has its uses on macOS where it's more common for a document window to scroll both horizontally and vertically.

Regarding emoji, I was thinking of Slack/Discord style emoji not the built-in Unicode emoji. In that case, we'd have an actual image, but wouldn't it to stretch the line height any larger than the text.

In any case, I have a more general solution, which I'm about to push up in a PR. Once I do that, I'll move our conversation over there to ensure that change meets your needs.

**Comment by andyfinnell** [comment]
Let's see if we can make #15 work for this use case.

**Pull request closed without merging**
